name: prose

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2
        with:
          files: docs
      - uses: errata-ai/vale-action@v2
        with:
          files: openspec
